<?php

	//PHP CAPTCHA image
	//Generated by https://www.html-code-generator.com/php/captcha-image-code-generator.php

	session_start();

	$width = 130;
	$height = 20;
	$font_size = 15;
	$font = "../fonts/verdana.ttf";
	$font = realpath($font);
	$chars_length = 6;

	$captcha_characters = '0123456789';

	$image = imagecreatetruecolor($width, $height);
	$bg_color = imagecolorallocate($image, 255, 255, 255);
	$font_color = imagecolorallocate($image, 0, 0, 0);
	imagefilledrectangle($image, 0, 0, $width, $height, $bg_color);

	//background ellipse
	$color = imagecolorallocate($image, 255, 5, 5);
	for ($i=0; $i < 30; $i++) {
		imageellipse($image, rand(0,$width), rand(0,$height), rand(5,100), rand(5,50), $color);
	}

	$xw = ($width/$chars_length);
	$x = 0;
	$font_gap = $xw/2-$font_size/2;
	$digit = '';
	for($i = 0; $i < $chars_length; $i++) {
		$letter = $captcha_characters[rand(0, strlen($captcha_characters)-1)];
		$digit .= $letter;
		if ($i == 0) {
			$x = 0;
		}else {
			$x = $xw*$i;
		}
		imagettftext($image, $font_size, 0, $x+$font_gap, rand(17, $height-5), $font_color, $font, $letter);
	}

	// record token in session variable
	$_SESSION['captcha_token'] = strtolower($digit);

	// display image
	header('Content-Type: image/png');
	imagepng($image);
	imagedestroy($image);
?>
